name: cim_model
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  aqueduct: 3.3.0+1

dev_dependencies:
  test: ^1.0.0

