POST http://127.0.0.1:8888/checkConnection
Content-Type: application/json

###

POST http://127.0.0.1:8888/auth/token
Content-Type: application/json

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin_again",
      "password" : "admin_again",
      "id" : "0",
      "role" : "0"
    }
  ]
}

###

GET http://127.0.0.1:8888/user/get
Authorization: Token e821244f-c6d1-4457-b079-3913ef7858ed
Content-Type: application/json

###

POST http://127.0.0.1:8888/user/update
Content-Type: application/json
Authorization: Token e821244f-c6d1-4457-b079-3913ef7858ed

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin1",
      "password" : "admin_new",
      "id" : "0"
    }
  ]
}

###

POST http://127.0.0.1:8888/user/new
Content-Type: application/json
Authorization: Token e821244f-c6d1-4457-b079-3913ef7858ed

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "user_2",
      "password" : "user_2_psw",
      "id" : "0",
      "role" : "1"
    }
  ]
}

###

GET http://127.0.0.1:8888/debug/clean_db
Authorization: Token e821244f-c6d1-4457-b079-3913ef7858ed
Content-Type: application/json

###

POST http://127.0.0.1:8888/user/first
Content-Type: application/json

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin_again2",
      "password" : "admin_again",
      "id" : "0",
      "role" : "0"
    }
  ]
}

###

