POST http://127.0.0.1:8888/checkConnection
Content-Type: application/json

###

POST http://127.0.0.1:8888/auth/token
Content-Type: application/json

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin_again",
      "password" : "admin_again",
      "id" : "0"
    }
  ]
}

###

GET http://127.0.0.1:8888/user/get
Authorization: Token 892b1035-5720-4325-8c45-cf410cad9a1d
Content-Type: application/json

###

POST http://127.0.0.1:8888/user/update
Content-Type: application/json
Authorization: Token 892b1035-5720-4325-8c45-cf410cad9a1d

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin1",
      "password" : "admin_new",
      "id" : "0"
    }
  ]
}

###

POST http://127.0.0.1:8888/user/new
Content-Type: application/json
Authorization: Token 892b1035-5720-4325-8c45-cf410cad9a1d

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin2",
      "password" : "admin2",
      "id" : "0"
    }
  ]
}

###

GET http://127.0.0.1:8888/debug/clean_db
Authorization: Token 892b1035-5720-4325-8c45-cf410cad9a1d
Content-Type: application/json

###

POST http://127.0.0.1:8888/user/first
Content-Type: application/json

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin_again",
      "password" : "admin_again",
      "id" : "0"
    }
  ]
}

###

