POST http://127.0.0.1:8888/checkConnection
Content-Type: application/json

###

POST http://127.0.0.1:8888/auth/token
Content-Type: application/json

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin_again",
      "password" : "admin_again",
      "id" : "0",
      "role" : "0"
    }
  ]
}

###

GET http://127.0.0.1:8888/user/get
Authorization: Token 8b684b55-e034-4b37-a56d-5e998dcc1694
Content-Type: application/json

###

POST http://127.0.0.1:8888/user/update
Content-Type: application/json
Authorization: Token 8b684b55-e034-4b37-a56d-5e998dcc1694

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin1",
      "password" : "admin_new",
      "id" : "0"
    }
  ]
}

###

POST http://127.0.0.1:8888/user/new
Content-Type: application/json
Authorization: Token 8b684b55-e034-4b37-a56d-5e998dcc1694

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin2",
      "password" : "admin2",
      "id" : "0"
    }
  ]
}

###

GET http://127.0.0.1:8888/debug/clean_db
Authorization: Token 8b684b55-e034-4b37-a56d-5e998dcc1694
Content-Type: application/json

###

POST http://127.0.0.1:8888/user/first
Content-Type: application/json

{
  "version" : "0.0.1",
  "instances" : [
    {
      "instance" : "CIMUser",
      "login" : "admin_again",
      "password" : "admin_again",
      "id" : "0",
      "role" : "0"
    }
  ]
}

###

