name: cim_server3
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  liquidart: 5.0.0-b7
  cim_protocol:
    path: ../cim_protocol-0.1.0/
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
