name: cim_server
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 4.0.0-b1
  cim_protocol:
    path: ../cim_protocol/


dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1

dependency_overrides:
  postgres: ^2.2.0

assets:
    - assets/certificate/